import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { FaArrowRightLong } from "react-icons/fa6";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        {/* footer*/}
        <div className="bg-white ">
          <div className="container mx-auto  px-8 ">
            <div className="lg:flex mt-20 mb-20">
              <div className="lg:w-8/12 w-full">
                <h1 className="lg:text-7xl text-3xl text-slate-950 font-medium lg:leading-snug leading-tight text-start">
                  Designing Tomorrow's <br />
                  Success Stories
                </h1>
                <div className="flex lg:gap-14 lg:flex-row flex-col mt-6">
                  <Link href="/">
                    <h3 className="text-slate-700 font-medium">Home</h3>
                  </Link>
                  <Link href="/">
                    <h3 className="text-slate-700 font-medium">Service</h3>
                  </Link>
                  <Link href="/">
                    <h3 className="text-slate-700 font-medium">About</h3>
                  </Link>
                  <Link href="/">
                    <h3 className="text-slate-700 font-medium">Product</h3>
                  </Link>
                  <Link href="/">
                    <h3 className="text-slate-700 font-medium">Contact</h3>
                  </Link>
                </div>
              </div>
              <div className="lg:w-4/12 w-full">
                <h2 className="text-slate-950 font-semibold text-2xl lg-:mt-0 mt-6">
                  Explore Our Portfolio <br />
                  Of Bespoke Designs <br />
                  Tailored
                </h2>
                <div className="bg-gray-100 border-2 lg:py-4 py-1 rounded-full w-fit lg:px-5 px-4 flex justify-between items-center lg:gap-44 gap-6 mt-12">
                  <div>
                    <input
                      type="text"
                      placeholder="Get Started"
                      className="border-none bg-gray-100 border-0 outline-none text-slate-950 placeholder:text-slate-950  "
                    />
                  </div>
                  <div>
                    <FaArrowRightLong className="text-red-500 hover:cursor-pointer" />
                  </div>
                </div>
              </div>
            </div>
            <div className="border-t-2 border-black flex justify-between py-6 text-slate-950 ">
              <h2> 2024 Pixel Perfect</h2>
              <h2>Copyright Alright Reserved</h2>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
